spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 55668899shang..
  mail:
    host: smtp.163.com
    port: 465  # 163邮箱的标准SSL端口
    username: 13736393394@163.com
    password: JKTMw6ea5YhqjjMH  # 请确认这是SMTP授权码而非邮箱密码
    protocol: smtps  # 使用smtps协议
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
          proxy:
            host:
            port:
          socks:
            host:
            port:
        transport:
          protocol: smtp
        debug: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null